version: '3.8'

services:
  apigatewayservice:
    build: .
    container_name: apigatewayservice
    ports:
      - '8080:8080'
    networks:
      discoverynetwork:

networks:
  discoverynetwork:
    external: true
