version: '3.8'

services:
  configserverservice:
    build: .
    container_name: configserverservice
    ports:
      - '8091:8091'
    networks:
      discoverynetwork:
networks:
  discoverynetwork:
    external: true
