version: '3.8'

services:
  inventoryservice:
    build: .
    container_name: inventoryservice
    depends_on:
      - dbInventory
    networks:
      inventorynetwork:
      discoverynetwork:
    ports:
      - '5111:5111'


  dbInventory:
    image: mysql:5.7.28
    container_name: dbInventory
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: inventoryService
    volumes:
      - mydbInventory:/var/lib/mysql
    networks:
      inventorynetwork:
    ports:
      - '3307:3306'
volumes:
  mydbInventory:
networks:
  discoverynetwork:
    external: true
  inventorynetwork:
    external: true
