version: '3.8'

services:
  dbInventory:
    image: mysql:5.7
    container_name: dbInventory
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: inventoryService
    volumes:
      - mydbInventory:/var/lib/mysql
    ports:
      - '3307:3306'
volumes:
  mydbInventory: