version: '3.8'

services:
  orderservice:
    build: .
    container_name: orderservice
#    ports:
#      - '8084:8082'
    depends_on:
      - databaseOrder
    networks:
      ordernetwork:
      discoverynetwork:
      inventorynetwork:
  databaseOrder:
    image: mysql:5.7
    container_name: databaseOrder
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: orderService
    volumes:
      - volumeOrder:/var/lib/mysql
    networks:
      ordernetwork:
#    ports:
#      - '3309:3306'
volumes:
  volumeOrder:
networks:
  ordernetwork:
  discoverynetwork:
    external: true
  inventorynetwork:
    external: true
