version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: orderService
    volumes:
      - mydb:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  mydb: