version: '3.8'

services:
  userservice:
    build: .
    container_name: userservice
#    ports:
#      - '5005:5005'
    networks:
      discoverynetwork:
networks:
  discoverynetwork:
    external: true
